// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWf0cNyOBI5kwPtInGVWKR80CvhKRVZzU',
    appId: '1:488288355720:web:5aac4eb26655c452faa63d',
    messagingSenderId: '488288355720',
    projectId: 'qcube-firebase-overview-ml',
    authDomain: 'qcube-firebase-overview-ml.firebaseapp.com',
    storageBucket: 'qcube-firebase-overview-ml.appspot.com',
    measurementId: 'G-GFBR5L0Y13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZhQSnjDIfXrOsaMwhNGdJbw2yBFrC5lQ',
    appId: '1:488288355720:android:85cd37786dc09782faa63d',
    messagingSenderId: '488288355720',
    projectId: 'qcube-firebase-overview-ml',
    storageBucket: 'qcube-firebase-overview-ml.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfrxyzJx2gsAyWu4ykviE0H_q3Qp1DUPM',
    appId: '1:488288355720:ios:4c55d796f118ed22faa63d',
    messagingSenderId: '488288355720',
    projectId: 'qcube-firebase-overview-ml',
    storageBucket: 'qcube-firebase-overview-ml.appspot.com',
    iosBundleId: 'com.example.ml',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfrxyzJx2gsAyWu4ykviE0H_q3Qp1DUPM',
    appId: '1:488288355720:ios:8cc3e34a58c98b26faa63d',
    messagingSenderId: '488288355720',
    projectId: 'qcube-firebase-overview-ml',
    storageBucket: 'qcube-firebase-overview-ml.appspot.com',
    iosBundleId: 'com.example.ml.RunnerTests',
  );
}
